<?php

namespace App\Providers;

use App\Contracts\TenantStorageContract;
use App\Services\Storage\TenantStorageService;
use Illuminate\Auth\Events\Login;
use Illuminate\Auth\Notifications\VerifyEmail;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        /* Storage is asked for by contract, so a test can hand a feature a
           different implementation and nothing in the feature changes. */
        $this->app->singleton(TenantStorageContract::class, TenantStorageService::class);

        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        /**
         * Stamp the last login, for the staff directory's "Last login" column.
         *
         * On the event rather than in a controller: Fortify, a passkey, a
         * remembered session and a future SSO all arrive at Login, and only
         * one of them goes through a form this application owns.
         */
        Event::listen(Login::class, function (Login $event) {
            $event->user->forceFill(['last_login_at' => now()])->saveQuietly();
        });

        /**
         * Verification email wording, per the specification.
         *
         * The signed URL is generated by the notification itself, so it keeps
         * Laravel's expiry and signature handling — only the copy is ours.
         * Expiry is configurable via auth.verification.expire.
         */
        VerifyEmail::toMailUsing(function (object $notifiable, string $url) {
            return (new MailMessage)
                ->subject('Verify your StyleDesk account')
                ->greeting('Welcome to StyleDesk.')
                ->line('Verify your email address to finish creating your account.')
                ->action('Verify Email', $url)
                ->line('If you did not create a StyleDesk account, you can ignore this email.');
        });

        //
    }
}
