<?php

namespace App\Providers;

use App\Contracts\TenantStorageContract;
use App\Http\Middleware\EnforceSessionTimeout;
use App\Services\Storage\TenantStorageService;
use Illuminate\Auth\Events\Login;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * The name to greet someone by.
     *
     * Falls back to their address when there is no name — a greeting that
     * reads "Hi ," is worse than one that reads a little formally.
     */
    private static function firstNameOf(object $notifiable): string
    {
        return $notifiable->first_name ?: (string) $notifiable->email;
    }

    /**
     * Register any application services.
     */
    public function register(): void
    {
        /* Storage is asked for by contract, so a test can hand a feature a
           different implementation and nothing in the feature changes. */
        $this->app->singleton(TenantStorageContract::class, TenantStorageService::class);

        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        /**
         * Stamp the last login, for the staff directory's "Last login" column.
         *
         * On the event rather than in a controller: Fortify, a passkey, a
         * remembered session and a future SSO all arrive at Login, and only
         * one of them goes through a form this application owns.
         */
        Event::listen(Login::class, function (Login $event) {
            $event->user->forceFill(['last_login_at' => now()])->saveQuietly();

            /**
             * A fresh sign-in starts a fresh idle clock.
             *
             * Regenerating the session on login changes its id but carries its
             * data across, so an idle stamp left by an earlier visit in the
             * same browser survives into the new session. Without this the
             * first request after signing in or signing up is measured against
             * the previous session's last activity, and someone who signed up
             * on a tab that had been open a while was signed straight back out
             * to the login page.
             *
             * Guarded because Login also fires where there is no session — a
             * console command, a queued job authenticating as a user.
             */
            if (request()->hasSession()) {
                request()->session()->put(EnforceSessionTimeout::KEY, now()->getTimestamp());
            }
        });

        /**
         * The account and security emails, on the shared branded template.
         *
         * Only the copy and the view are ours: the token, its expiry and its
         * signature are still generated by Laravel's own notifications, so
         * nothing about how these links are trusted changes here.
         *
         * `view` rather than `markdown`, because the template is a hand-built
         * table layout — mail clients strip stylesheets, and Laravel's
         * markdown mail renders through a theme this does not use.
         *
         * Verification is the exception and lives in App\Notifications\VerifyEmail
         * instead: its email carries a six-digit code as well as a link, and a
         * static callback has nowhere to receive a value minted per send.
         */
        ResetPassword::toMailUsing(function (object $notifiable, string $token) {
            return (new MailMessage)
                ->from(config('mail.auth_from.address'), config('mail.auth_from.name'))
                ->subject('Reset your StyleDesk password')
                ->view('emails.auth.reset-password', [
                    'firstName' => self::firstNameOf($notifiable),
                    'url' => url(route('password.reset', [
                        'token' => $token,
                        'email' => $notifiable->getEmailForPasswordReset(),
                    ], false)),
                    'expiresInMinutes' => config('auth.passwords.'.config('auth.defaults.passwords').'.expire'),
                ]);
        });

        //
    }
}
